Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 190, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 134, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.25_eps_0.0008/5m_18d_20h_51m_20s_chi2.dat.lock'
srun: error: cn044: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 190, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 141, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.25_eps_0.0008/5m_18d_20h_51m_20s_enu_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 190, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 147, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.25_eps_0.0008/5m_18d_20h_51m_20s_evis_spectrum.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 190, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 163, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.25_eps_0.0008/5m_18d_20h_51m_20s_invmass_spectrum.dat.lock'
srun: error: cn044: task 0: Exited with exit code 1
srun: error: cn044: task 0: Exited with exit code 1
srun: error: cn044: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 190, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 134, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.25_eps_0.0008/5m_18d_20h_51m_20s_chi2.dat.lock'
srun: error: cn044: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 190, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 134, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.25_eps_0.0008/5m_18d_20h_51m_20s_chi2.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 190, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 134, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.25_eps_0.0008/5m_18d_20h_51m_20s_chi2.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 190, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py", line 134, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.25_eps_0.0008/5m_18d_20h_51m_20s_chi2.dat.lock'
srun: error: cn027: task 0: Exited with exit code 1
srun: error: cn027: task 0: Exited with exit code 1
srun: error: cn027: task 0: Exited with exit code 1
/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py:125: RuntimeWarning: invalid value encountered in double_scalars
  eff_selection = df_tot["reco_w"].sum() / df_tot["w_event_rate"].sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py:128: RuntimeWarning: invalid value encountered in double_scalars
  eff_geometry = df_tot["w_event_rate"].sum() / df_tot["w_pre_decay"].sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py:130: RuntimeWarning: invalid value encountered in double_scalars
  eff_final = df_tot["reco_w"].sum() / df_tot["w_pre_decay"].sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py:125: RuntimeWarning: invalid value encountered in double_scalars
  eff_selection = df_tot["reco_w"].sum() / df_tot["w_event_rate"].sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py:128: RuntimeWarning: invalid value encountered in double_scalars
  eff_geometry = df_tot["w_event_rate"].sum() / df_tot["w_pre_decay"].sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/SymmetryFit/fit_3p2_general.py:130: RuntimeWarning: invalid value encountered in double_scalars
  eff_final = df_tot["reco_w"].sum() / df_tot["w_pre_decay"].sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:269: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
