Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 154, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.15_eps_0.001/5m_10d_21h_21m_47s_costheta_spectrum.dat.lock'
srun: error: cn005: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.15_eps_0.001/5m_10d_21h_21m_47s_enu_spectrum.dat.lock'
srun: error: cn028: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.15_eps_0.001/5m_10d_21h_21m_47s_chi2.dat.lock'
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.15_eps_0.001/5m_10d_21h_21m_47s_enu_spectrum.dat.lock'
srun: error: cn028: task 0: Exited with exit code 1
srun: error: cn028: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 138, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.15_eps_0.001/5m_10d_21h_21m_47s_enu_spectrum.dat.lock'
srun: error: cn012: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.15_eps_0.001/5m_10d_21h_21m_47s_chi2.dat.lock'
srun: error: cn006: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 146, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.15_eps_0.001/5m_10d_21h_21m_47s_evis_spectrum.dat.lock'
srun: error: cn006: task 0: Exited with exit code 1
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:264: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:264: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/analysis.py:264: RuntimeWarning: invalid value encountered in double_scalars
  df["reco_eff"] = w_selection.sum() / w.sum()
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.15_eps_0.001/5m_10d_21h_21m_47s_chi2.dat.lock'
srun: error: cn062: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 154, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.15_eps_0.001/5m_10d_21h_21m_47s_costheta_spectrum.dat.lock'
srun: error: cn062: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 164, in fit_point_3p2
    gf.save_to_locked_file(
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.15_eps_0.001/5m_10d_21h_21m_47s_invmass_spectrum.dat.lock'
srun: error: cn032: task 0: Exited with exit code 1
Traceback (most recent call last):
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 198, in <module>
    fit_point_3p2(
  File "/home/mhostert/DarkNews/singlefit/fit_3p2_general.py", line 131, in fit_point_3p2
    gf.save_to_locked_file(path + "chi2.dat", output)
  File "/home/mhostert/DarkNews/MiniBooNE-DarkNews/src/fastbnb/grid_fit.py", line 38, in save_to_locked_file
    os.remove(lockfile_name)
FileNotFoundError: [Errno 2] No such file or directory: 'results/3p2_general_mzprime_m4_0.15_eps_0.001/5m_10d_21h_21m_47s_chi2.dat.lock'
srun: error: cn016: task 0: Exited with exit code 1
